FROM apache/airflow:2.10.5-python3.11

USER airflow

RUN pip install --no-cache-dir \
    dbt-postgres==1.9.0 \
    pandas==2.2.3 \
    SQLAlchemy==1.4.54 \
    psycopg2-binary==2.9.10 \
    PyYAML==6.0.2 \
    openai==3.26.1
