version: 2

models:
  - name: fct_bookings
    description: One row per booking.
    columns:
      - name: booking_id
        data_tests:
          - not_null
          - unique
      - name: hotel_id
        data_tests:
          - relationships:
              arguments:
                to: ref('dim_hotels')
                field: hotel_id

  - name: dim_hotels
    description: One row per hotel.
    columns:
      - name: hotel_id
        data_tests:
          - not_null
          - unique
